# Generated by Django 5.2.5 on 2025-10-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('car_servicing', 'Car Servicing'), ('battery_check', 'Battery Check'), ('mechanical_repair', 'Mechanical Repair'), ('tyre_replacement', 'Tyre Replacement'), ('ac_service', 'AC Service'), ('preventive_maintenance', 'Preventive Maintenance')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
    ]
